"""empty message

Revision ID: 76175bd702b0
Revises: 3191df03a3a9
Create Date: 2025-01-30 11:05:27.885520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76175bd702b0'
down_revision = '3191df03a3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_subjects')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_present', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_days_opened', sa.Integer(), nullable=False))
        batch_op.drop_column('attendance_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('attendance_date', sa.DATE(), nullable=False))
        batch_op.drop_column('total_days_opened')
        batch_op.drop_column('days_present')

    op.create_table('teacher_subjects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
