"""empty message

Revision ID: 12adc889e71c
Revises: 1e9884aee574
Create Date: 2025-02-23 13:05:29.932847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12adc889e71c'
down_revision = '1e9884aee574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_user_id', type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_student_id', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_student_id', 'students', ['student_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_students_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
