"""empty message

Revision ID: 62bfeb6103ab
Revises: 33564d15b8b1
Create Date: 2025-02-26 11:36:32.746217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62bfeb6103ab'
down_revision = '33564d15b8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_teacher_id', 'teachers', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_teacher_id', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
