"""empty message

Revision ID: 960139cf41d7
Revises: cd7528f0a805
Create Date: 2025-02-24 09:54:35.707404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960139cf41d7'
down_revision = 'cd7528f0a805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('result_url')

    # ### end Alembic commands ###
