"""empty message

Revision ID: 9ef31cbb562c
Revises: 97480c164a67
Create Date: 2025-03-01 14:30:02.980322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef31cbb562c'
down_revision = '97480c164a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_subject_scores', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assessment_subject_scores_student_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_subject_scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_assessment_subject_scores_student_id', 'students', ['student_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###
