"""empty message

Revision ID: b1730e824a8e
Revises: 960139cf41d7
Create Date: 2025-02-24 16:27:22.121281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1730e824a8e'
down_revision = '960139cf41d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_remark', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('principal_remark', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('principal_remark')
        batch_op.drop_column('teacher_remark')

    # ### end Alembic commands ###
