"""empty message

Revision ID: c283ca4f8416
Revises: b1730e824a8e
Create Date: 2025-02-25 08:31:39.243965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c283ca4f8416'
down_revision = 'b1730e824a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal_signature', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('principal_signature')

    # ### end Alembic commands ###
