"""empty message

Revision ID: cd7528f0a805
Revises: 5c738b5f8687
Create Date: 2025-02-23 13:25:55.950416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7528f0a805'
down_revision = '5c738b5f8687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_student_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_users_student_id', 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_student_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_users_student_id', 'users', ['student_id'], ['id'])

    # ### end Alembic commands ###
