"""empty message

Revision ID: 2662f8ee83a1
Revises: a88f458747fc
Create Date: 2025-02-18 08:55:08.233888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2662f8ee83a1'
down_revision = 'a88f458747fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_types', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_assessment_per_school', ['name', 'school_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_types', schema=None) as batch_op:
        batch_op.drop_constraint('unique_assessment_per_school', type_='unique')

    # ### end Alembic commands ###
