"""empty message

Revision ID: 3191df03a3a9
Revises: 
Create Date: 2025-01-25 15:41:59.378603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3191df03a3a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        # Add the column with a default value to avoid errors in SQLite
        batch_op.add_column(sa.Column('term', sa.String(length=20), nullable=False, server_default='Default Term'))
    
    # Remove the default value after column creation if not needed
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.alter_column('term', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('term')

    # ### end Alembic commands ###

