"""empty message

Revision ID: a88f458747fc
Revises: 18a5ac6aa5e5
Create Date: 2025-02-17 19:30:48.056257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88f458747fc'
down_revision = '18a5ac6aa5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_assessment_type_school', 'schools', ['school_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assessment_type_school', type_='foreignkey')
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
