"""Fix assessment type uniqueness per school

Revision ID: b0438a997294
Revises: 2662f8ee83a1
Create Date: 2025-02-18 09:10:27.519293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0438a997294'
down_revision = '2662f8ee83a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_types', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('unique_assessment_per_school', type_='unique')
        batch_op.create_unique_constraint('uq_assessment_per_school', ['name', 'school_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_types', schema=None) as batch_op:
        batch_op.drop_constraint('uq_assessment_per_school', type_='unique')
        batch_op.create_unique_constraint('unique_assessment_per_school', ['name', 'school_id'])
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
