"""empty message

Revision ID: c3cd53780b58
Revises: b0438a997294
Create Date: 2025-02-18 11:18:34.774593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3cd53780b58'
down_revision = 'b0438a997294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_types', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('unique_assessment_per_school', type_='unique')
        batch_op.create_unique_constraint('uq_assessment_per_school', ['name', 'school_id'])

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_assessment_per_school', ['name', 'school_id'])

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_class_per_school', ['class_name', 'school_id'])

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_subject_per_school', ['name', 'school_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_subject_per_school', type_='unique')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_class_per_school', type_='unique')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_assessment_per_school', type_='unique')

    with op.batch_alter_table('assessment_types', schema=None) as batch_op:
        batch_op.drop_constraint('uq_assessment_per_school', type_='unique')
        batch_op.create_unique_constraint('unique_assessment_per_school', ['name', 'school_id'])
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
