"""empty message

Revision ID: 2624f7920703
Revises: 
Create Date: 2025-02-18 16:41:48.597600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2624f7920703'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fee_payments')
    with op.batch_alter_table('fee_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year', sa.String(length=10), nullable=False, server_default='2024/2025'))
        batch_op.add_column(sa.Column('term', sa.String(length=20), nullable=False, server_default='First Term'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_components', schema=None) as batch_op:
        batch_op.drop_column('term')
        batch_op.drop_column('academic_year')

    op.create_table('fee_payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_fee_id', sa.INTEGER(), nullable=False),
    sa.Column('amount_paid', sa.FLOAT(), nullable=False),
    sa.Column('payment_date', sa.DATE(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('receipt_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['student_fee_id'], ['student_fees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
